#! /bin/sh

# Git credential helper, simply returns password transferred in 1st command line parameter.
# Must be registered in git config in the following form:
#  [credential "<domain name>"]
#	  helper = repeater <repo pass>

if [ $2 = "get" ]; then
	echo "password=$1"
fi